trigger:
  - CypressTestsUseCases

stages:
  - stage: e2e_testing_stage_fireox
    displayName: 'firefox E2E Testing'
    jobs:
      - job: e2e_testing_job_chrome
        displayName: 'Run E2E tests in firefox'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - template: e2e.testing.yml
            parameters:
              browserType: firefox 
      - job: e2e_testing_job_chrome
        displayName: 'Run E2E tests in Chrome'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - template: e2e.testing.yml
            parameters:
              browserType: chrome
      - job: e2e_testing_job_chrome
        displayName: 'Run E2E tests in firefox'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - template: e2e.testing.yml
            parameters:
              browserType: edge 
    # add additional stages for testing other browsers
