trigger:
  - none
schedules:
#  - cron: '0 18 * * *'  # summer time
  - cron: '0 19 * * *'  # winter time
    displayName: 'Run cypress tests on 20:00 daily build'
    branches:
      include:
      - main
    always: true
stages:
  - stage: e2e_testing_stage_chrome
    displayName: 'Chrome E2E Testing'
    jobs:
      - job: e2e_testing_job_chrome
        displayName: 'Run E2E tests in Chrome'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - template: e2e.testing.yml
            parameters:
              browserType: chrome
  - stage: e2e_testing_stage_edge
    displayName: 'Edge E2E Testing'
    jobs:
      - job: e2e_testing_job_firefox
        displayName: 'Run E2E tests in Edge'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - template: e2e.testing.yml
            parameters:
              browserType: edge
# add additional stages for testing other browsers
