trigger:
  - CypressTestsUseCases

stages:
  - stage: e2e_testing_stage_chrome
    displayName: 'chrome E2E Testing'
    jobs:
      - job: e2e_testing_job_chrome
        displayName: 'Run E2E tests in Chrome'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - template: e2e.testing.yml
            parameters:
              browserType: electron
    # add additional stages for testing other browsers
