steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
      displayName: 'Install Node.js'    
  # Install Node dependencies
  - script: npm ci
    displayName: 'Install NPM dependencies'

  - script: npx cypress verify
    displayName: 'Cypress verify'

  - script: npx cypress info
    displayName: 'Cypress info'

  - script: |
      npx cypress run --browser ${{ parameters.browserType }} --reporter junit
    displayName: 'Run Cypress tests'
    env:
      # avoid warnings about terminal
      TERM: xterm

  - task: PublishTestResults@2
    displayName: 'publish test results'
    condition: always()
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/gb3-test-output-*.xml'
      failTaskOnFailedTests: true

  - task: PublishBuildArtifacts@1
    displayName: 'publish screenshots'
    condition: always()
    inputs:
      pathToPublish: 'cypress/screenshots'
      artifactName: screenshots-${{ parameters.browserType }}
    continueOnError: true